sealtk/gui/Player.cpp
Don't bother storing the individual connections to a video source; it isn't necessary, as we can (and should) just disconnect everything instead.
=> Simplify signals/slots in gui::Player

sealtk/noaa/Main.cpp
Modify entry point to stack allocate the main window, rather than heap allocating it. This is important because the main window needs to be destroyed before (or at least, during) the destruction of the `QApplication`, or Bad Things (note [[1]](https://lists.qt-project.org/pipermail/interest/2019-March/032807.html) [[2]](https://lists.qt-project.org/pipermail/interest/2019-March/032817.html)) can happen.
=> Don't "leak" main window

CMakeLists.txt, cmake/SEALTKUtils.cmake, cmake/setup_KWIVER.bat.in, cmake/setup_KWIVER.sh.in
Modify the logic that controls where build artifacts are written to also use the GNU directories. This makes the build tree more consistent with the install tree.
=> Also use GNU install dirs for build tree

sealtk/gui/Player.cpp, sealtk/noaa/Main.cpp
Enable global context sharing, which allows us to be more conservative about recreating OpenGL resources. Convert said resources to regular member objects rather than smart pointers, as the extra level of indirection is now unnecessary.
Note that we still need "clean-up" logic for our textures, as `QOpenGLTexture` retains a pointer to the `QOpenGLFunctions` instance of the context with which it was created, which leads to a crash in Qt code trying to reuse the `QOpenGLTexture` after a context change, even though the underlying OpenGL resource is fine. (This seems like a bug...)
=> Simplify management of OpenGL resources

sealtk/core/KwiverVideoSource.cpp, sealtk/core/KwiverVideoSource.hpp, sealtk/core/TimeMap.hpp, sealtk/core/VideoController.cpp, sealtk/core/VideoSource.hpp, sealtk/core/test/KwiverVideoSource.cpp, sealtk/core/test/VideoController.cpp, sealtk/gui/Player.cpp, sealtk/noaa/test/ImageListVideoSourceFactory.cpp
Modify `VideoSource` to more explicitly work with a `TimeMap` for seeking, and to provide the complete `TimeMap` upon request rather than a `QSet` (which, as an unordered collection, is somewhat likely to be unhelpful on its own). Modify its signals to consolidate the cases where data is available and where data is not available, as we were not effectively making use of the latter as distinct from passing a null pointer via the former. Include the time stamp in these signals, which will be useful for users performing newly-possible inexact seeks. Modify `KwiverVideoSource` to accomodate these changes. Modify unit tests likewise.
This should help with certain use cases where sequential rather than random access is desired.
=> Improve VideoSource API

sealtk/core/KwiverFileVideoSourceFactory.cpp, sealtk/core/test/CMakeLists.txt, sealtk/core/test/KwiverVideoSource.cpp, sealtk/core/test/TestCommon.cpp, sealtk/core/test/VideoController.cpp, sealtk/noaa/gui/Window.cpp
Avoid use of aforementioned methods, which assume that the `std::string` is / should be UTF-8. While this is almost certainly correct on Linux, it is almost as surely *wrong* on Windows. Instead, use the `qtString` and `stdString` functions from qtStlUtil which use `QString::{to,from}Local8Bit` under the hood.
=> Don't use QString::{to,from}StdString

sealtk/core/CMakeLists.txt, sealtk/core/KwiverVideoSource.cpp, sealtk/core/VideoMetaData.cpp, sealtk/core/VideoMetaData.hpp, sealtk/core/VideoSource.hpp, sealtk/noaa/test/ImageListVideoSourceFactory.cpp
Modify `VideoSource` to provide a new `VideoMetaData` instance along with the available image, rather than just a time stamp. This new class includes the time stamp, and will also include other information that is useful to the GUI (for now, also the image name).
We are using our own class here in order to also include the time stamp, which has providence separate from the metadata provided by the KWIVER `video_input`, and also because there is a bit of cognitive dissonance between the GUI's notion of metadata, which is generally frame-specific, and the KWIVER notion where metadata is a separate data stream independent of the frame images. However, in the future we may modify our class to also provide the raw KWIVER metadata.
=> Add "metadata" to video sources

sealtk/core/TimeMap.hpp
Add a "private" type alias `Key`, which allows us to greatly simplify a lot of code due to not needing to repeat the overly long actual type name. Replace `typedef X Y` used to 'import' types from the base `QMap` with `using X`, which works just as well for such cases. Replace most constructors and destructor with explicit defaulting rather than providing equivalent definitions. Add explicitly defaulted assignment operators. Refactor implementation of `find` to be a private member rather than a namespace (which slightly improves security by making it more difficult for non-implementation code to call the method). Improve code formatting.
Besides all the general tidying, this avoids a warning about use of a deprecated implicit assignment operator.
The code is much less "new" than the diff …
=> Do some tidying of TimeMap.hpp

sealtk/core/DateUtils.cpp, sealtk/core/DateUtils.hpp, sealtk/core/test/DateUtils.cpp
Add additional convenience methods to convert a `timestamp::time_t` or `QDateTime` to a string representing either the date or the time as text. These will be useful for UI's that want to show date/time to the user.
=> Add conversions to date/time strings

CMakeLists.txt, cmake/SEALTKUtils.cmake, sealtk/gui/CMakeLists.txt, sealtk/gui/Player.cpp, sealtk/gui/Player.hpp, sealtk/gui/resources/PlayerFragment.glsl, sealtk/noaa/gui/Window.cpp
Add new "contrast mode" options to `gui::Player`. The options are `Manual` (user specifies minimum and maximum values) and `Percentile` (uses `AutoLevelsTask` to compute values). This also includes the logic to keep track of computed percentile levels per time-keyed image, and to fire off new tasks as needed.
Modify NOAA GUI to use Percentile mode for the IR view. (For now, this is hard-coded, as are the tolerance and deviation values.)
=> Hook up level control in Player

sealtk/core/CMakeLists.txt, sealtk/core/DataModelTypes.cpp, sealtk/core/DataModelTypes.hpp, sealtk/gui/AbstractItemModel.cpp, sealtk/gui/AbstractItemModel.hpp, sealtk/gui/AbstractItemRepresentation.cpp, sealtk/gui/AbstractItemRepresentation.hpp, sealtk/gui/CMakeLists.txt, sealtk/gui/test/AbstractItemRepresentation.cpp, sealtk/gui/test/CMakeLists.txt, utilities/source_check.py
Add base classes for item data models, and representations of item data. The latter is more or less imported wholesale from [ViViA](https://github.com/kitware/vivia), while the former adds some minor convenience features. The representation class defines a mechanism by which the underlying model can provide data in a representation-agnostic manner, and serves as a base class for implementing representations.
Also, tweak `source_check.py` to skip the copyright check on "trivial" C++ sources (defined as a file consisting of a single comment). This avoids adding a mostly-gratuitous copyright notice to `DataModelTypes.cpp`, which exists only to trigger CMake's automoc, and whose entire contents consists of a comment explaining this.
=> Create base classes for item data

sealtk/gui/Player.cpp
Modify `gui::Player` to disassociate itself from its video source when the source is destroyed. I suspect this has been broken, but wasn't noticed because a) the application only ever destroys a video source when replacing it with a new one, and b) prior to the new video API, the old source was only destroyed after assigning the new source to the `Player`. When the new API was introduced (#21), the application logic also changed to destroy the old source first, which would leave the `Player` with a dangling reference.
This should fix #27.
=> Fix crash when changing video source

sealtk/gui/Player.cpp
Modify `gui::Player` to reset any computed percentile levels (and also change the cookie, so any pending computations will be ignored) when the video source changes. This fixes incorrectly carrying over previously computed levels to different images that happen to have the same time stamps.
This should fix #30.
=> Reset computed levels when video source changes

sealtk/gui/AbstractItemRepresentation.hpp, sealtk/gui/CMakeLists.txt, sealtk/gui/Enums.cpp, sealtk/gui/Enums.hpp, sealtk/gui/Player.hpp
Having two instances of Q_NAMESPACE causes issues with Qt, so move
all enums into one file.
=> Fix duplicate Q_NAMESPACE issue

sealtk/core/test/ImageUtils.cpp
GCC 4.8 chokes on raw string literals passed as arguments to a macro, which are used by the aforementioned unit test. Work around this by redefining `QStringLiteral` → `QString` when using GCC 4.8, which results in constructing a `QString` using the string literal constructor (`QString(char const*)`) instead. This is less efficient, but at least it compiles.
GCC 4.8 also insists on an unnecessary space between the quotes and suffix of a user-defined literal operator. (Clang 3.1 does also, but later compilers don't require it. It seems this was an early restriction in UDL definitions that was subsequently relaxed.)
(While we're at it, also make the UDL's `constexpr`; they really ought to be...)
=> Fix ImageUtils test on GCC 4.8

CMakeLists.txt
Modify finding Qt to explicitly require Qt ≥ 5.10. We actually require this already, due to use of features added in 5.10; this just arranges to get an explicit version-mismatch error at configure time rather than less obvious build errors.
=> Explicitly require Qt ≥ 5.10

sealtk/gui/Player.cpp, sealtk/gui/Player.hpp, sealtk/noaa/gui/Player.cpp, sealtk/noaa/gui/Player.hpp, sealtk/noaa/gui/Window.cpp
Modify `noaa::gui::Player` to have a notion of a "master" window and "slave" windows, with the latter able to use a transformation to map their local space to the "master"'s space. Implement logic to allow the user to load such a transformation.
This uses a `vital::transform` (note: depends on kitware/kwiver#790) under the hood, which can include non-linear transformations. Eventually we want to handle those better; for now, we approximate by computing a homography matrix by mapping our image corner points.
This is a "static" transformation in that the user loads a single transformation for the entire data set (as opposed to having a separate transformation per frame). Eventually we will probably want to add support for per-frame transformations as well, which will likely rely on the …
=> Use homography

sealtk/gui/CMakeLists.txt, sealtk/gui/FusionModel.cpp, sealtk/gui/FusionModel.hpp, sealtk/gui/test/CMakeLists.txt, sealtk/gui/test/FusionModel.cpp, sealtk/noaa/Main.cpp, sealtk/noaa/gui/Player.cpp, sealtk/noaa/gui/Window.cpp, sealtk/noaa/gui/Window.ui
Update NOAA GUI to use new `KwiverTrackSource`. Create `FusionModel`. Use this to implement a "detections"¹ list to the NOAA GUI.
(¹ As far as implementation, this is actually a *track* list, but NOAA only deals with tracks consisting of a single detection, and we use "detections" in the UI.)
=> Add "detections" (track) list to GUI

sealtk/noaa/Main.cpp, sealtk/noaa/gui/Window.cpp, sealtk/noaa/gui/Window.hpp
Add UI state persistence to the NOAA GUI. This way users can arrange things to their liking and not have to redo it every time they restart the application.
(Depends on kitware/qtextensions#26.)
=> Save UI state of NOAA GUI

sealtk/core/AbstractItemModel.cpp, sealtk/core/AbstractProxyModel.cpp, sealtk/core/AbstractProxyModel.hpp, sealtk/core/CMakeLists.txt, sealtk/core/DataModelTypes.hpp, sealtk/core/KwiverTrackModel.cpp, sealtk/core/KwiverTrackModel.hpp, sealtk/core/ScalarFilterModel.cpp, sealtk/core/ScalarFilterModel.hpp, sealtk/core/test/CMakeLists.txt, sealtk/core/test/ScalarFilterModel.cpp, sealtk/core/test/TestTracks.cpp, sealtk/core/test/TestTracks.hpp, sealtk/gui/AbstractItemRepresentation.cpp, sealtk/gui/AbstractItemRepresentation.hpp, sealtk/gui/FusionModel.cpp, sealtk/gui/Player.cpp, sealtk/gui/Player.hpp, sealtk/gui/test/AbstractItemRepresentation.cpp, sealtk/noaa/gui/Window.cpp
Add detections/states to `KwiverTrackModel`, so that we have a way with the new data model framework to get bounding boxes. Add `ScalarFilterModel`, to filter a model based on scalar bounds, which will be used to determine what boxes should be shown on a given frame. Update detection rendering code to use these.
=> (Re)implement track rendering

sealtk/gui/Player.cpp
Tweak our code to set the scene transform (homography) to also force an update of the view transform. This is needed because the view transform depends on whether or not we have a non-identity scene transform active. Previously, the view would not update correctly when a scene transform is initially loaded.
I believe this is correct, but it would be good if @mattdawkins could also test.
=> Update view transform on changing scene transform

sealtk/core/TimeMap.hpp, sealtk/core/test/TimeMap.cpp
Add meta-information to the `SeekMode` enumeration used by `TimeMap`. Modify the `TimeMap` test to directly pass the seek mode. Also, improve the test names and an explanatory comment, and fix some style inconsistencies.
Depends on kitware/qtextensions#28.
=> TimeMap test polishing

sealtk/gui/Player.cpp
Tweak detection rendering code to account for vertices being tuples, while our vertex data array is an array of scalars. This was causing us to render too many vertices, and (sort of) at the wrong offsets. This appears to have gone unnoticed as apparently OpenGL has built-in out of bounds protection, and simply doesn't do anything when asked to render indices that don't exist.
=> Fix vertex indices in detection rendering

sealtk/core/AbstractItemModel.cpp, sealtk/core/AbstractItemModel.hpp, sealtk/core/AbstractProxyModel.cpp, sealtk/core/AbstractProxyModel.hpp, sealtk/core/CMakeLists.txt, sealtk/core/KwiverPipelinePortSet.cpp, sealtk/core/KwiverPipelinePortSet.hpp, sealtk/core/KwiverPipelineWorker.cpp, sealtk/core/KwiverTrackModel.cpp, sealtk/core/ScalarFilterModel.cpp, sealtk/gui/FusionModel.cpp, sealtk/gui/Player.cpp, sealtk/gui/test/FusionModel.cpp, sealtk/noaa/core/CMakeLists.txt, sealtk/noaa/core/NoaaPipelineWorker.cpp, sealtk/noaa/core/NoaaPipelineWorker.hpp, sealtk/noaa/gui/Window.cpp
Fix several issues with data models and consumers thereof (mostly related to properly handling updates). Create new `NoaaPipelineWorker` class to extract detections from a pipeline, producing a dynamically-updating track model for pipelines which have detection output ports. Modify `noaa::gui::Window` to consume these track models.
=>  Implement getting detections from pipelines

sealtk/core/KwiverTrackModel.cpp
KWIVER recently changed (kitware/kwiver#860) `object_track_state::detection` from a member to an accessor function. Update our code accordingly.
=> Update for recent KWIVER changes

sealtk/core/KwiverTrackModel.cpp, sealtk/gui/FusionModel.cpp, sealtk/noaa/gui/CMakeLists.txt, sealtk/noaa/gui/TrackTypeDelegate.cpp, sealtk/noaa/gui/TrackTypeDelegate.hpp, sealtk/noaa/gui/Window.cpp
Hook up ability to change the type of a "detection" (i.e. track) in the NOAA GUI. This is a very rough-and-ready implementation, but for now it should be functional.
=> Allow "editing" track types

sealtk/gui/AbstractItemRepresentation.cpp, sealtk/noaa/gui/Window.ui
Remove root decoration in NOAA track list; at least for now, it serves no purpose. Fix text alignment of classification score.
=> Fix some minor aesthetic issues

sealtk/noaa/gui/Window.cpp, sealtk/noaa/gui/Window.ui
Add a View menu to the NOAA GUI, with the (persisted) ability to toggle whether or not the IR pane is visible.
=> Add ability to hide IR pane in NOAA GUI

sealtk/core/AbstractProxyModel.cpp
More specifically, when comparing values during the sort, if they are both integers use integer compare. Otherwise, continue to sort as strings.
=> If the name column contains ids, sort as integers

sealtk/core/AbstractItemModel.cpp, sealtk/core/KwiverTrackModel.cpp
Use `std::sort` instead of `qSort` per deprecation warning. Add missing `break`s in `switch` (fixes a fall-through warning, might fix bugs).
=> Little fixes

CMakeLists.txt, cmake/SEALTKUtils.cmake
Modify CMake code to request full C++14. Apparently this does work with GCC 4.8.x, even though that was some ways from full C++14 support, whereas requesting C++11 plus the required additional features does not. While there was a plan to fix this at one point, apparently it is not going to happen, and this is the "sanctioned" way to use C++1y with GCC 4.8.
=> "Require" C++14

sealtk/noaa/Main.cpp
QIcon::setFallbackThemeName was added in Qt 5.12. The VIAME superbuild
uses Qt 5.11.2, so this function is not supported.
=> Remove fallback icon theme

sealtk/noaa/CMakeLists.txt, sealtk/noaa/PluginConfig.hpp.in, sealtk/noaa/core/ImageListVideoSourceFactory.cpp, sealtk/noaa/gui/Window.cpp
An ongoing issue has been that we expect the NOAA GUI to be built to use KWIVER plugins from an additional dependency (VIAME), but don't want this dependency to be mandatory. As a result, we have been maintaining a branch that changes some of the plugins used.
Instead, arrange for the ability to configure the relevant plugin selection at configure time. This maintains our goal of minimizing dependencies out-of-the-box, but will make it possible to punt plugin selection to configure time, rather than having to maintain a branch to change the defaults.
=> Make NOAA GUI plugins configurable

utilities/source_check.py
Modify the source check script to ignore QRC files when checking copyrights. As these are effectively just lists of resource files to be compiled in, there is little value in even asserting copyright (which technically isn't necessary anyway), and these files are subject to being rewritten by Designer, which strips any notice we try to add.
=> Don't check copyrights on QRC files

sealtk/noaa/kwiver/TimestampPassthrough.hpp
Don't use the now-deprecated `algorithm_impl` wrapper class for our `TimestampPassthrough` algorithm.
See also Kitware/kwiver#757.
@linus-sherrill, can you also please verify that this is the intended fix?
=> Don't use deprecated algorithm class
